apiVersion: v1
kind: Namespace
metadata:
  name: employee-dir

---

apiVersion: v1
kind: Service
metadata:
  namespace: employee-dir
  name: employee-dir-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: employee-dir
  name: employee-dir-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: employee-dir
        image: 992382381749.dkr.ecr.us-west-2.amazonaws.com/employee-directory
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---


